version: "3.0"
services: 
  web:
    build: ngix\.
    ports:
      - "8011:80"
    links:
      - "iis1"
      - "iis2"
  iis1:    
    image:  iis2
  iis2:    
    build:  aspcore2\.
    image:  iis2        
networks:
    default:
        driver: bridge